### ISSUE TITLE
Need to update launch screen with design from Christina Chin

### ISSUE THREAD

**Issue by StevenPrescott** [StevenPrescott/swift_runnerapp#2]
![i3 cimgpsh_orig](https://cloud.githubusercontent.com/assets/7350775/11018054/021eae20-857c-11e5-9ac9-cc6e4a0b4af2.png)

**Comment by StevenPrescott** [comment]
will handle this in the AM or ASAP

**Comment by ashkanNe** [comment]
Fixed this. Will close on next commit
