### ISSUE TITLE
Need to implement new first-time user push notification request screen

### ISSUE THREAD

**Issue by StevenPrescott** [StevenPrescott/swift_runnerapp#3]
![i4 cimgpsh_orig](https://cloud.githubusercontent.com/assets/7350775/11018062/43bfa6a4-857c-11e5-993a-1b9b8170cd67.png)

**Comment by ashkanNe** [comment]
I'll work on that. Text me the color hex.

**Comment by ashkanNe** [comment]
Fixed design. Will push commits later. You'll need to implement the actual technical aspect.
